//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportLife
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Gets and sets informations about your diet from/in database
    /// </summary>
    public partial class macrosandtdee
    {
        public int Id { get; set; }
        public Nullable<int> wtdee { get; set; }
        public Nullable<int> deficyt { get; set; }
        public Nullable<int> needeat { get; set; }
        public Nullable<int> protein { get; set; }
        public Nullable<int> fat { get; set; }
        public Nullable<int> carbs { get; set; }
    }
}
