//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportLife
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Gets and sets informations about your diet from/in database
    /// </summary>
    public partial class macrosandtdee
    {
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Gets or sets the wtdee.
        /// </summary>
        public Nullable<int> wtdee { get; set; }
        /// <summary>
        /// Gets or sets the deficyt.
        /// </summary>
        public Nullable<int> deficyt { get; set; }
        /// <summary>
        /// Gets or sets the needeat.
        /// </summary>
        public Nullable<int> needeat { get; set; }
        /// <summary>
        /// Gets or sets the protein.
        /// </summary>
        public Nullable<int> protein { get; set; }
        /// <summary>
        /// Gets or sets the fat.
        /// </summary>
        public Nullable<int> fat { get; set; }
        /// <summary>
        /// Gets or sets the carbs.
        /// </summary>
        public Nullable<int> carbs { get; set; }
    }
}
