//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportLife
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Gets and sets informations about your measures from/in database
    /// </summary>
    public partial class MEASURES
    {
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Gets or sets the weight.
        /// </summary>
        public Nullable<int> weight { get; set; }
        /// <summary>
        /// Gets or sets the age.
        /// </summary>
        public Nullable<int> age { get; set; }
        /// <summary>
        /// Gets or sets the height.
        /// </summary>
        public Nullable<int> height { get; set; }
        /// <summary>
        /// Gets or sets the activity.
        /// </summary>
        public Nullable<int> activity { get; set; }
        /// <summary>
        /// Gets or sets the weightchange.
        /// </summary>
        public Nullable<int> weightchange { get; set; }
    }
}
