//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportLife
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Gets and sets informations about runs statistics from/in database
    /// </summary>
    public partial class statisticRuns
    {
        public int Id { get; set; }
        public Nullable<int> distance { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> userID { get; set; }
    }
}
