//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportLife
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class databaseEntities : DbContext
    {
        public databaseEntities()
            : base("name=databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<macrosandtdee> macrosandtdee { get; set; }
        public virtual DbSet<MEASURES> MEASURES { get; set; }
        public virtual DbSet<RUNSSTATISTICS> RUNSSTATISTICS { get; set; }
        public virtual DbSet<TDEEDATA> TDEEDATA { get; set; }
    }
}
