//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportLife
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Gets and sets informations about users from/in database
    /// </summary>
    public partial class users
    {
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Gets or sets the login.
        /// </summary>
        public string login { get; set; }
        /// <summary>
        /// Gets or sets the password.
        /// </summary>
        public string password { get; set; }
    }
}
